export const GET_TOKEN_PENDING = "GET_TOKEN_PENDING";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

export const UPDATE_USER = "UPDATE_USER";

export const SIGNUP_PENDING = "SIGNUP_PENDING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const REGISTER_TEAM_PENDING = "REGISTER_TEAM_PENDING";
export const REGISTER_TEAM_SUCCESS = "REGISTER_TEAM_SUCCESS";
export const REGISTER_TEAM_FAILURE = "REGISTER_TEAM_FAILURE";
