export const GET_TOKEN_PENDING = "GET_TOKEN_PENDING";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

export const INITIALIZE_USER = "INITIALIZE_USER";
export const UPDATE_USER_TEAM = "UPDATE_USER_TEAM";

export const REGISTER_TEAM_PENDING = "REGISTER_TEAM_PENDING";

export const REGISTER_TEAM_FAILURE = "REGISTER_TEAM_FAILURE";
